### ISSUE TITLE
Valiables may be used before initialization

### ISSUE THREAD

**Issue by RaulPPelaez** [stochasticHydroTools/SlenderBody#3]
https://github.com/stochasticHydroTools/SlenderBody/blob/6a29cc60c32a1bb9d98dfb3b84630ca89a7ee74d/Python/cppmodules/SpecialQuadratures.cpp#L61

There should be an "else" clause here:

https://github.com/stochasticHydroTools/SlenderBody/blob/6a29cc60c32a1bb9d98dfb3b84630ca89a7ee74d/Python/cppmodules/SpecialQuadratures.cpp#L68-L77

Or alternatively, initialize imin1,2 to some default, harmless, value. Even if the situation is impossible, it shuts up compiler warnings.

**Comment by omaxian** [comment]
Ok, situation impossible but I initialized to 0 to stop the warnings.
