### ISSUE TITLE
Check Lapacke calls

### ISSUE THREAD

**Issue by RaulPPelaez** [stochasticHydroTools/SlenderBody#4]
I had to modify these lines to be able to compile:
https://github.com/stochasticHydroTools/SlenderBody/blob/993253127234377374fae21f5def49ab7e67a0f5/Python/cppmodules/SpecialQuadratures.cpp#L421-L429

This is how they were before:
https://github.com/stochasticHydroTools/SlenderBody/blob/e3a682f55c261052b13d72cf56a7f3de656e34f4/Python/cppmodules/SpecialQuadratures.cpp#L422-L424

My installation of lapacke (Fedora 35 installed from official repos) does not provide these functions. They are called LAPACKE_*
The documentation for this function is here:
http://www.netlib.org/lapack/explore-html/de/ddd/lapacke_8h_a044782d17dd9592ab7d2b5b4f5c0f7a7.html#a044782d17dd9592ab7d2b5b4f5c0f7a7

And it requires a Matrix layout argument that was missing in the previous commit. I put LAPACK_ROW_MAJOR, but I do not know if it is COL_MAJOR instead. Please check and change if needed.

No idea where the *_ functions come from, but they look to me like implementation detail functions.

**Comment by omaxian** [comment]
It should be COL_MAJOR. I fixed it in the latest commit.
