### ISSUE TITLE
Visualization issue

### ISSUE THREAD

**Issue by Nasrollah** [stochasticHydroTools/SlenderBody#7]
To whom it may concern,

I have some data obtained from SlenderBody source code and need to visualize it. I know that a python package called "PlotOptix" is required for that. However, I do not know whether or not I should install it seperately and I need a license for that.
Furthermore, I have seen a python script in "plots" directory which seems suitable to visualization. However, I do not know how to use that.

I would be wondering if you could kindly guide me on these issues related to visualization.

Yours sincerely,
Nasrollah Hajaliakbari

**Comment by omaxian** [comment]
Nasrollah,

First of all, just so you know, I have finally finished the documentation for the software. You can find it [here](slenderbody.readthedocs.io). [This page](https://slenderbody.readthedocs.io/en/latest/CrossLinkedExamples.html) in particular talks about what the outputs of your simulation mean. 

For analyzing the output and visualization, there are a few options:
1) [This Matlab file](https://github.com/stochasticHydroTools/SlenderBody/blob/master/Matlab/AnalyzePython/ProcessPythonNetwork.m) will read in the statistics from the simulation and plot the results. You can modify it to also plot the locations at each time step (the file Locs(FileString).txt has the locations of the Chebyshev points). 
2) Another option is to use [PlotOptix](https://plotoptix.rnd.team/) to make fancy visualizations. This requires a GPU, however. If you want to do that, I typically use [this Matlab file](https://github.com/stochasticHydroTools/SlenderBody/blob/master/Matlab/AnalyzePython/MakePlotConfigs.m) to generate a set of .txt files for the locations at each time step. Then, as you mentioned, there is a file in the [plots directory](https://github.com/stochasticHydroTools/SlenderBody/blob/master/Python/plots/BundledFibers.py) which takes those .txt files, as well as *.txt files with the cross link locations, as inputs and will plot the networks. 
3) You can make your own plotting tools using Matplotlib in Python or whatever software you prefer.

I apologize as the tools we have for visualization are not as user friendly, so this will be a back and forth process. Let me know how I can be of help. 

Thanks,

Ondrej Maxian

**Comment by Nasrollah** [comment]
Dear Dr. Ondrej Maxian

Thanks for your response and providing the documentation as a good tool for analyzing the inputs and outputs for this source code.
Related to visualization, I want to use both matlab and plotOptix.
At first, I tried to use matlab. To do that, I used your script file called “ProcessPythonNetwork.m “. However, I got this error in below and I have these questions related to that.
“
Unrecognized function or variable 'chebpts'.
“

1-Which version of Matlab you are using?
2-It seems that the function ” chebpts” is not existed in matlab in default. As a result, how should I provide and add that in matlab?

I would be wondering if you could kindly answer my questions.

Best regards,
Nasrollah Hajaliakbari

**Comment by omaxian** [comment]
You need to install chebfun:
https://www.chebfun.org/

**Comment by Nasrollah** [comment]
Dear Dr. Ondrej Maxian,

Thanks for your response and providing the link. Based on that, I have successfully read the data using some scripts in MATLAB to analyze the results (first option). There was only a small typo, like a bug in here:

“
https://github.com/stochasticHydroTools/SlenderBody/blob/master/Matlab/AnalyzePython/ProcessPythonNetwork.m#L51
“
Right now, I am working with plotoptix to do the visualization (second option). Based on your explanation, I have generated a set of .txt files for the locations at each time step from my results. However, I can see in the python script (BundledFibers.py) that there is still a file lacking, called “Colormap.txt”.  I suppose it must be provided for the python script in order to be run. I would be wondering if you could kindly provide a template file for that until I can visualize the results.

Best regards,
Nasrollah Hajaliakbari

**Comment by omaxian** [comment]
Nasrollah,

The colormap is up to you. You can generate it in Matlab via
`cmap = colormap(winter)
writematrix(cmap,'cmap.txt','delimiter',',')`
for example (although "winter" is not a great map). See [this page](https://www.mathworks.com/help/matlab/ref/colormap.html) for a list of color maps.

OM

**Comment by Nasrollah** [comment]
Dear Dr. Ondrej Maxian,

Thanks for your response.
After spending some time on visualization, I realized that I have some problems in using "plotoptix", since I want to create some contours which is not straightforward and also lack of handy GPUs here. As a result, I decided to use other software. 
I tried to write some codes for visualization and I could succeessfully visualize only the fibers but not the domain. To visualize the domain, I need to have a separate file in which the coordinates of eights domain’s corners have been dumped when the fibre locations are dumped. However, I do not know how to implement that (I do not know which of these files I must change:  StrainDynamicNetwork.py, DomainC.cpp, Domain.py).
I would be wondering if you could possibly provide some hints for me about that.

Best regards,
Nasrollah Hajaliakbari

**Comment by Nasrollah** [comment]
Dear Dr. Ondrej Maxian,

Thanks for your respone and providing the info. 
I implemented that into my code. However, the domain does not quite fit into the fibers. I needed to double the size of the domain (from 2 to 4) (I am visualizing the results of the tutorial, I mean StrainDynamicNetwork.py), but there is a kind of offset here. I do not know what would be the coordinates of the domain center (relative to the fibers). I would be wondering if you could kindly guide me on this issue as well.

Best regards,
Nasrollah Hajaliakbari

**Comment by omaxian** [comment]
The fiber locations won't ever be strictly inside the periodic box. The computations that involve periodicity do that, but they don't get saved in that way. If you want particles to be inside the box, I typically use this code, where again $g$ is the strain
```
# Translate particles in z and y until they are on [0,L] in those directions
    xyz[:,2]-=np.floor(xyz[:,2]/Lp)*Lp
    yshift = np.floor(xyz[:,1]/Lp)*Lp
    xyz[:,1]-=yshift;
    xyz[:,0]-=g*yshift;
    # Translate particles in x until they sit in parallelogram
    xyz[:,0]-=np.floor(xyz[:,0]/Lp)*Lp # Now they are sitting on [0,L]
    #print(np.max(np.abs(xyz)))
    #np.savetxt('FibersDiameterApart.txt',xyz)
    if (g > 0):
        inds = xyz[:,1] > 1/g*xyz[:,0]
        xyz[inds,:]+=[Lp,0,0]; 
    elif (g < 0):
        inds = xyz[:,1] > 1/g*(xyz[:,0]-Lp)
        xyz[inds,:]-=[Lp,0,0]; 
```

**Comment by Nasrollah** [comment]
Dear Dr. Ondrej Maxian,

Thanks for your response and support.

Best regards,
Nasrollah Hajaliakbari
